apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-cfsplugin
  labels:
    name: data-cfsplugin
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3000Gi
  csi:
    driver: csi-cfsplugin
    volumeHandle: data-id
    volumeAttributes:
      cfsMaster1: 10.10.2.4:80
      cfsMaster2: 10.10.2.5:80
      cfsMaster3: 10.10.2.6:80
      volName: intest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-cfsplugin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3000Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["data-cfsplugin"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: "IfNotPresent"
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: data-cfsplugin
  volumes:
  - name: data-cfsplugin
    persistentVolumeClaim:
      claimName: data-cfsplugin
